### Матрицы и матричные операции. Часть 1

In [3]:
import numpy as np

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

По опредедению, матрица m x k и матрица n x l можно перемножить. если m = l, размерность полученной матрицы получается m x l.

a) A (4X2) * B(4X2) и B * A - произведение не определено (4 != 2)

б) A(2X5) * B(5X3) проиведение не определено (2!=3), B(5X3) * A(2X5) - произведение возможно, размерность получаемой матрицы  = 5Х5

в) А(8Х3) * В(3Х8) - произведение возможно, размерность полученной матрицы = 8Х8
   В(3Х8) * В(8Х3) - определено, размерность 3Х3

г) A(4Х4) * B(4Х) и В*А - определены, размерность 4Х4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [7]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1],[0, 5]])

In [8]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [9]:
A @ B

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

In [11]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [13]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [95]:
A = [[1, -2], [3,0]]
B = [[4, -1], [0, 5]]

In [98]:
def matrix_dot(A,B):
    s = 0     #сумма
    T = []    #временная матрица
    C = []    #конечная матрица
    if len(B) != len(A[0]):
        print ("Неверная размерность, матрицы не могут быть перемножены.")        
    else:
        r1 = len(A) #количество строк в первой матрице
        c1 = len(A[0]) #Количество столбцов в 1   
        r2 = len(B)     # количество строк во 2ой матрице
        c2 = len(B[0])  # количество столбцов во 2ой матрице
        for z in range(0,r1):
            for j in range(0,c2):
                for i in range(0,c1):
                   s=s+A[z][i]*B[i][j]
                T.append(s)
                s = 0
            C.append(T)
            T = []           
    return C

In [99]:
matrix_dot(A,B)

[[4, -11], [12, -3]]

### Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

   a)$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

In [71]:
A = np.array([[np.sin(1), -np.cos(1)],[np.cos(1), np.sin(1)]])

In [72]:
np.linalg.det(A)

1.0

б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [74]:
A = np.array([[4,2,3],[0,5,1],[0,0,9]])
np.linalg.det(A)

180.0

в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [75]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)

6.66133814775094e-16

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) 16
б) 4
в) 8

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [87]:
A = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])

In [88]:
np.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [90]:
A = np.array([[1,2,3],[1,1,1],[2,3,4]])

In [91]:
np.linalg.matrix_rank(A)

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [92]:
A = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
np.linalg.matrix_rank(A)

3