## Урок 5. Сингулярное разложение матриц

In [69]:
import numpy as np

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [70]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])

In [71]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [72]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]


In [73]:
print(f'Матрица U:\n{U}')


Матрица U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]


In [74]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1.00000000e+00 -1.26634814e-16  2.43728648e-16  6.93889390e-17
   2.77555756e-17]
 [-1.26634814e-16  1.00000000e+00 -1.31838984e-16 -1.00613962e-16
  -2.77555756e-17]
 [ 2.43728648e-16 -1.31838984e-16  1.00000000e+00  1.73472348e-18
  -1.38777878e-17]
 [ 6.93889390e-17 -1.00613962e-16  1.73472348e-18  1.00000000e+00
  -2.77555756e-17]
 [ 2.77555756e-17 -2.77555756e-17 -1.38777878e-17 -2.77555756e-17
   1.00000000e+00]]


In [75]:
print(f'Матрица V:\n{V}')


Матрица V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]


In [76]:
print(np.dot(V.T, V))


[[1.00000000e+00 1.11022302e-16 2.77555756e-17]
 [1.11022302e-16 1.00000000e+00 0.00000000e+00]
 [2.77555756e-17 0.00000000e+00 1.00000000e+00]]


In [77]:
print(np.dot(np.dot(U, D), V.T))


[[ 1.00000000e+00  2.00000000e+00 -1.72084569e-15]
 [-6.66133815e-16  6.66133815e-16  5.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  6.00000000e+00  5.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00  0.00000000e+00]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [81]:
#через библиотеку
print(f'Норма Евклида = {np.linalg.norm(A,ord=2)}')

Норма Евклида = 8.824868854820442


In [82]:
#через диагональную матрицу сингулярного разложения
print(s[0])

8.824868854820448


In [83]:
#по формуле из исходной матрицы
print(f'Норма Фробениуса = {np.sqrt(np.sum(A*A))}')

Норма Фробениуса = 11.045361017187261


In [84]:
#через библиотеку
print(f'Норма Фробениуса = {np.linalg.norm(A)}')

Норма Фробениуса = 11.045361017187261


In [85]:
#через диагональную матрицу сингулярного разложения
np.sqrt(np.sum(s*s))

11.045361017187265